---
root: true
parserOptions:
  ecmaVersion: 2017
env:
  browser: true
  es6: true
rules:
  max-len:
    - warn
    - 120
  indent:
    - error
    - tab
    - SwitchCase: 1
  camelcase:
    - error
    - properties: always
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  comma-dangle:
    - error
    - never
  dot-notation:
    - error
  semi:
    - error
    - always
